# Generated by Django 5.2.7 on 2025-10-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
