# Generated by Django 4.2 on 2025-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_pedido_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
