# Generated by Django 4.2 on 2025-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('camiseta', 'Camiseta'), ('calca', 'Calça'), ('short', 'Short'), ('vestido', 'Vestido'), ('acessorio', 'Acessório'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(),
        ),
    ]
